class Login_model {
  String? message;
  Admin? admin;
  String? token;

  Login_model({this.message, this.admin, this.token});

  Login_model.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    admin = json['admin'] != null ? new Admin.fromJson(json['admin']) : null;
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    if (this.admin != null) {
      data['admin'] = this.admin!.toJson();
    }
    data['token'] = this.token;
    return data;
  }
}

class Admin {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? mobile;
  int? isBanned;
  int? status;
  int? isAutoGeneratedPassword;
  String? createdAt;
  String? updatedAt;

  Admin(
      {this.id,
      this.firstName,
      this.lastName,
      this.email,
      this.mobile,
      this.isBanned,
      this.status,
      this.isAutoGeneratedPassword,
      this.createdAt,
      this.updatedAt});

  Admin.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    mobile = json['mobile'];
    isBanned = json['is_banned'];
    status = json['status'];
    isAutoGeneratedPassword = json['is_auto_generated_password'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['email'] = this.email;
    data['mobile'] = this.mobile;
    data['is_banned'] = this.isBanned;
    data['status'] = this.status;
    data['is_auto_generated_password'] = this.isAutoGeneratedPassword;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
